/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MB;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muaaz Bhyat
 */
public class EditGUI extends javax.swing.JFrame {

    private int auth = 3;
    private String username;

    /**
     * Creates new form EditGUI
     */
    public EditGUI() {
        initComponents();
    }

    public EditGUI(String usr) {
        initComponents();
        title.setText("Edit Info For " + usr);
        username = usr;
    }

    public EditGUI(String usr, int a) {
        initComponents();
        title.setText("Edit Info For " + usr);
        PatientManager pm = new PatientManager(usr);
        this.prepScreen(pm.getKnown(usr));
        auth = a;
        username = usr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        errTxt = new javax.swing.JLabel();
        TrustedDocTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BloodTypeTxt = new javax.swing.JTextField();
        AllergensTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IDNoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FullNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CellNoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HomeNoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Edit Data For Username");
        jPanel1.add(title);
        title.setBounds(0, 10, 500, 50);

        SaveBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SaveBtn.setText("Save & Close");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SaveBtn);
        SaveBtn.setBounds(10, 240, 150, 33);

        btnHelp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp);
        btnHelp.setBounds(520, 240, 150, 33);

        errTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        errTxt.setForeground(new java.awt.Color(255, 51, 51));
        errTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(errTxt);
        errTxt.setBounds(160, 290, 500, 50);

        TrustedDocTxt.setFocusCycleRoot(true);
        TrustedDocTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(TrustedDocTxt);
        TrustedDocTxt.setBounds(170, 70, 150, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Trusted Doc. Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 150, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Allergens: (Please use ',' to seperate diffrent allergens)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 150, 320, 30);

        BloodTypeTxt.setFocusCycleRoot(true);
        BloodTypeTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(BloodTypeTxt);
        BloodTypeTxt.setBounds(170, 110, 150, 30);

        AllergensTxt.setFocusCycleRoot(true);
        AllergensTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(AllergensTxt);
        AllergensTxt.setBounds(330, 150, 310, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Blood Type:*");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 150, 30);

        IDNoTxt.setFocusCycleRoot(true);
        IDNoTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(IDNoTxt);
        IDNoTxt.setBounds(490, 70, 150, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID No.*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 70, 150, 30);

        FullNameTxt.setFocusCycleRoot(true);
        FullNameTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(FullNameTxt);
        FullNameTxt.setBounds(490, 110, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Full Name*");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 110, 150, 30);

        CellNoTxt.setFocusCycleRoot(true);
        CellNoTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(CellNoTxt);
        CellNoTxt.setBounds(170, 180, 150, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cell No.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 150, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Home No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 190, 150, 30);

        HomeNoTxt.setFocusCycleRoot(true);
        HomeNoTxt.setFocusTraversalPolicyProvider(true);
        jPanel1.add(HomeNoTxt);
        HomeNoTxt.setBounds(490, 190, 150, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("* indicates required field");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 330, 150, 17);

        CloseBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CloseBtn);
        CloseBtn.setBounds(260, 240, 150, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        String temp = "";
        
        boolean flag = true;
        PatientManager pm = new PatientManager(username);
        MasterValidator vm = new MasterValidator();
        if (vm.isStringEmpty(FullNameTxt.getText()) || vm.isStringEmpty(IDNoTxt.getText()) || vm.isStringEmpty(BloodTypeTxt.getText())) {
            errTxt.setText("Please make sure all required fields are filled in");
        } else {
            if (vm.isStringTooLong(BloodTypeTxt.getText().trim(), 3)) {
                temp += "Please make sure Blood type is no more than 3 chraracters,";
                flag = false;
            }
            if ((CellNoTxt.getText().trim().length() != 10 && !vm.isStringEmpty(CellNoTxt.getText())) || (HomeNoTxt.getText().trim().length() != 10 && !vm.isStringEmpty(HomeNoTxt.getText()))) {
                temp += "Please check Cellphone and Tell No. length,";
                flag = false;
            }
            if (IDNoTxt.getText().trim().length() != 13 && !vm.isStringEmpty(IDNoTxt.getText())) {
                temp += "Please Check ID. No.,";
                flag = false;
            }
//            if (!vm.isStringEmpty(TrustedDocTxt.getText()) && vm.isStringTooShort(TrustedDocTxt.getText(), 8)) {
//                temp += "Please make sure Doc Username is gretaer than 8";
//                flag = false;
//            }
            if (flag) {
                String update = "";
                update += IDNoTxt.getText().trim() + ";";
                update += FullNameTxt.getText().substring(0, FullNameTxt.getText().lastIndexOf(" ")) + ";";
                update += FullNameTxt.getText().substring(FullNameTxt.getText().lastIndexOf(" ")).trim() + ";";
                update += CellNoTxt.getText().trim() + ";";
                update += HomeNoTxt.getText().trim() + ";";
                update += AllergensTxt.getText().trim() + ";";
                update += BloodTypeTxt.getText().trim() + ";";
                update += TrustedDocTxt.getText().trim() + " " ;
                System.out.println(update);
                pm.SaveChanges(update);
                

                switch (auth) {
                    case 0: {
                        MainScreenGUI2 msc = new MainScreenGUI2(username, 3);
                        msc.setVisible(true);
                        this.dispose();
                        break;
                    }
                    case 1: {
                        MainScreenGUI3 msc = new MainScreenGUI3(username, 4);
                        msc.setVisible(true);
                        this.dispose();
                        break;
                    }
                    default: {
                        MainScreenGUI msc = new MainScreenGUI(username, 1);
                        msc.setVisible(true);
                        this.dispose();
                        break;
                    }
                }

            }
        }
        errTxt.setText(temp);
        title.setText("Edit Info For " + username);
        
        this.prepScreen(pm.getKnown(username));

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpScreenUi hs = new HelpScreenUi();
        hs.setVisible(true);
        hs.setFocusable(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    
    
    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        switch (auth) {
            case 0:
                {
                    MainScreenGUI2 msc = new MainScreenGUI2(username, 3);
                    msc.setVisible(true);
                    this.dispose();
                    break;
                }
            case 1:
                {
                    MainScreenGUI3 msc = new MainScreenGUI3(username, 4);
                    msc.setVisible(true);
                    this.dispose();
                    break;
                }
            default:
                {
                    MainScreenGUI2 msc = new MainScreenGUI2(username, 3);
                    msc.setVisible(true);
                    this.dispose();
                    break;
                }
        }
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void prepScreen(String s) {
        Scanner sc = new Scanner(s).useDelimiter(";");
        IDNoTxt.setText(sc.next());
        FullNameTxt.setText(sc.next());
        BloodTypeTxt.setText(sc.next());
        AllergensTxt.setText(sc.next());
        CellNoTxt.setText(sc.next());
        HomeNoTxt.setText(sc.next());
        TrustedDocTxt.setText(sc.next());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllergensTxt;
    private javax.swing.JTextField BloodTypeTxt;
    private javax.swing.JTextField CellNoTxt;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField FullNameTxt;
    private javax.swing.JTextField HomeNoTxt;
    private javax.swing.JTextField IDNoTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TrustedDocTxt;
    private javax.swing.JButton btnHelp;
    private javax.swing.JLabel errTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
